POST http://localhost:3000/api/stuff
Content-Type: application/json

{
    "_id": "12345ass6",
    "title": "My second thing",
    "description": "All of about my things",
    "imageUrl": "",
    "price": 3900,
    "userId": "2311111s1111"
}